"""Add category and is_available to Tool

Revision ID: a92911962cfc
Revises: 
Create Date: 2025-02-18 22:00:24.295237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a92911962cfc'
down_revision = None
branch_labels = None
depends_on = None


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('tool', schema=None) as batch_op:
#         batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=False))
#         batch_op.add_column(sa.Column('is_available', sa.Boolean(), nullable=True))
def upgrade():
    with op.batch_alter_table("tool") as batch_op:
        batch_op.add_column(sa.Column("category", sa.String(length=50), nullable=False, server_default="Other"))
        batch_op.add_column(sa.Column("is_available", sa.Boolean(), nullable=False, server_default="1"))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool', schema=None) as batch_op:
        batch_op.drop_column('is_available')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
