name: CI

on: push

jobs:
  linter-check:
    name: Linter Check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install poetry
        poetry install -v

    - name: Lint with flake8
      run: |
        make lint
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v2.7.4
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      with:
        coverageCommand: make test-coverage
        debug: true
